#!/usr/bin/env python3

import json
import os
import pathlib
import sys


def main():
    if len(sys.argv) != 2:
        print("Script called with incorrect number of arguments")
        exit(2)  # Incorrect script usage

    [_, path] = sys.argv
    path = pathlib.Path(path).resolve()
    bench_script_path = path / "bench"

    try:
        os.execv(bench_script_path, [bench_script_path, path])
    except OSError as e:
        msg = f"Could not run benchmark script at {bench_script_path}: {e}"
        print(json.dumps({"error": msg}))


if __name__ == "__main__":
    main()
